#!/bin/sh
set -eu

: "${DRAGONFLY_SYSROOT:=/mnt/t2}"
: "${DRAGONFLY_USE_LD:=gold}"

exec /usr/bin/clang \
  --target=x86_64-unknown-dragonfly \
  --sysroot="${DRAGONFLY_SYSROOT}" \
  -fuse-ld="${DRAGONFLY_USE_LD}" \
  "$@"
